###post producer message
POST {{producer}}/producer/sendmsg
Content-Type: application/json

{
  "topic": "ApiService",
  "key": "a",
  "partition": [0],
  "value": "4"
}

###get test
GET {{producer}}/producer/receivemsg?topic=ApiService&partition=0

###producer
POST {{producer}}/producer/sendmsg
Content-Type: application/json

{
  "topic": "ApiService",
  "partition": [0],
  "key": "",
  "value": "hello from http request"
}