###test transaction service without jwt token(SHOULD NOT WORK)
POST {{transaction_host}}/storage/transaction/deposit?encrypted_transaction=123

###test transaction service with jwt token
POST {{transaction_host}}/storage/transaction/deposit
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODExMzE2MzIsInVzZXJfbmFtZSI6ImFkMjMgMzIwMjAyMDIwMjAyIiwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiNWFmMjE2ODctYjRkZi00YTNlLWFhNzMtMzY5YzQ0YWQ5MzlhIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAiLCJzY29wZSI6WyJhbGwiXX0.iz8VkCBpMn4R2lXbQu62MGXU-ex9ctSd47Cs0cjKtQM
content-type:Application/json

{
  "transaction":"dB1j+wlWlbpm2JApjkhBUptuuBuLAOFnmhXf9zAMTG9Je6n1Y9OkwIsKlg5gRyX1"
}

###test email generation
POST {{transaction_host}}/storage/transaction/generateEmail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODEyOTMyNTAsInVzZXJfbmFtZSI6ImFkMjQgMzIwMjAyMDIwMjAzIiwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiYTU2NmI5ODUtZTY3ZS00MmYxLTk5ZWUtMDRjN2RjNGE3ODg1IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAiLCJzY29wZSI6WyJhbGwiXX0.uWU85-q0wxE8lBeczveC2oC4qjPH-NFLKmdyQrtaWkE

###test email generation
OPTIONS {{transaction_host}}/storage/transaction/generateEmail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODEyOTMyNTAsInVzZXJfbmFtZSI6ImFkMjQgMzIwMjAyMDIwMjAzIiwiYXV0aG9yaXRpZXMiOlsicDEiXSwianRpIjoiYTU2NmI5ODUtZTY3ZS00MmYxLTk5ZWUtMDRjN2RjNGE3ODg1IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAiLCJzY29wZSI6WyJhbGwiXX0.uWU85-q0wxE8lBeczveC2oC4qjPH-NFLKmdyQrtaWkE

###test open account
POST {{transaction_host}}/storage/account/open
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYmFua19hcHBsaWNhdGlvbiJdLCJ1c2VyX25hbWUiOiJhZDIzIDMyMDIwMjAyMDIwMiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODEzNzc2MjIsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImQxNDIwMjkzLWFmNDUtNDlhZS05OWE2LTYwZGM1OWJkOGFjZCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.fR3qK5DmKfuWLnpvoWUWf7ZQT7vHX7JBBpWPgJWSb1Q