server:
  servlet:
    context-path: /api
  port: 63050
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_application_credit
    username: root
    password: youpassword
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: Bank_Application
        group: bank_application

  application:
    name: ApiService
logging:
  config: classpath:log4j2-dev.xml