spring:
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_application
    username: root
    password: youpassword
server:
  servlet:
    context-path: /auth
  port: 63010 # 网关端口
logging:
  config: classpath:log4j2-dev.xml