export const storage_url = "http://localhost:63020/storage"
export const auth_url = "http://localhost:63010"
export const credit_url = "http://localhost:63040"
export const gateway_url = "http://localhost:63000"
export const frontend_url = "http://localhost:9091"
export const api_url = "http://localhost:63050"
export const audit_url = "http://localhost:63060"